id: A84A79C89
base_file: f7379.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:05:58.892241
  last_modified_at: 2022-05-30 23:05:58.892250
